# Generated by Django 3.0.4 on 2020-03-20 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20200320_0350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weapons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='armor',
            name='finch',
        ),
    ]
