# Generated by Django 3.0.4 on 2020-03-20 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20200320_0354'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Weapons',
        ),
    ]
