# Generated by Django 3.0.4 on 2020-03-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_delete_weapons'),
    ]

    operations = [
        migrations.AddField(
            model_name='finch',
            name='armor',
            field=models.ManyToManyField(to='main_app.Armor'),
        ),
    ]
